FROM odoo:18.0

# Copy custom addons
COPY ./infra/odoo/addons /mnt/extra-addons

# Expose Odoo port
EXPOSE 8069

# Start Odoo
CMD ["sh", "-c", "exec odoo --without-demo=all --db_sslmode=${DB_SSLMODE:-require}"]
