FROM odoo:18.0

# Copy custom addons
COPY ./infra/odoo/addons /mnt/extra-addons

# Expose Odoo port
EXPOSE 8069

# Start Odoo
CMD ["sh", "-c", "exec odoo --without-demo=all --http-port=8069 --db_host=\"${DB_HOST:?DB_HOST is required}\" --db_port=\"${DB_PORT:-5432}\" --db_user=\"${DB_USER:?DB_USER is required}\" --db_password=\"${DB_PASSWORD:-${PASSWORD:?DB_PASSWORD or PASSWORD is required}}\" --db_sslmode=\"${DB_SSLMODE:-require}\""]
