services:
  # Odoo Web Service (using external PostgreSQL from Layerbase)
  - type: web
    name: cdt-odoo-web
    runtime: docker
    plan: free
    dockerfilePath: ./infra/odoo/Dockerfile.web
    envVars:
      - key: HOST
        sync: false
      - key: PORT
        value: 5432
      - key: USER
        sync: false
      - key: PASSWORD
        sync: false
      - key: MAILCHIMP_API_KEY
        sync: false
      - key: MAILCHIMP_LIST_ID
        sync: false
      - key: CDT_NEWSLETTER_SHARED_SECRET
        sync: false
